name: CI
on: [push, pull_request]
permissions:
  contents: read
jobs:
  tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install project
        run: |
          poetry check
          poetry install --no-interaction
      - name: Run pre-commit
        run: poetry run pre-commit run --all-files --verbose
      - name: Pull DVC data
        run: poetry run dvc pull
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
      - name: Run DVC pipelines
        run: poetry run dvc repro -f dags/salary/catboost/dvc.yaml
      - name: Run tests
        run: poetry run pytest
