name: CI
on: [push, pull_request]
permissions:
  contents: read
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install project
        run: |
          poetry check
          poetry install --no-interaction
      - name: DVC get data
        run: |
          poetry run dvc remote modify predicting_models_nba_games --local gdrive_use_service_account true
          poetry run dvc pull
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
      - name: DVC run dags
        run: poetry run dvc repro -f dags/salary/catboost/dvc.yaml
      - name: Run tests
        run: poetry run pytest
